<h1 style="font-size:20; text-align:center; color:red">Objectifs</h1>

Les objectifs de cet exercice sont :
1. Importer des données provenant du web et les lire en tant que dataframe
2. Obternir des informations basiques sur la structure des données.

<h1 style="font-size:20; text-align:center; color:red; font-family:bold">Importation des données</h1>

In [10]:
# Importez la librairie Pandas

import pandas as pd

In [21]:
# Sources des données

file = 'https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'

# Importez les données en tant que dataframe pandas

df = pd.read_csv(file)

# Affichez les 10 premières lignes de la dataframe

df.head(10)

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.60,...,130,mpfi,3.47,2.68,9.00,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
5,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
6,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
7,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
8,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430

Les données n'ont pas une ligne de noms de colonnes. Vous remarquez que la première observationn a été utilisée comme noms de colonnes. Pour corrisger cela, vous devez retrouvez les noms de colonnes à partir de ce lien https://archive.ics.uci.edu/ml/datasets/automobile et les stocker dans une liste

In [17]:
# Créez une liste de stockage des noms de colonnes

colones = ["symbling", "normalized-losses", "make",
            "fuel-type", "aspiration", "num-of-doors",
            "body-style", "drive-wheels", "engine-location",
            "wheel-base", "length", "width", "height",
            "curb-weight", "engine-type", "num-of-cylinders",
            "engine-size", "fuel-system", "bore", "stroke",
            "compression-ratio", "horsepower", "paek-rmp",
            "city-mpg", "highway-mpg", "price"]

# Afficher la liste : colonnes

colonnes

['symbling',
 'normalized-losses',
 'make',
 'fuel-type',
 'aspiration',
 'num-of-doors',
 'body-style',
 'drive-wheels',
 'engine-location',
 'wheel-base',
 'length',
 'width',
 'height',
 'curb-weight',
 'engine-type',
 'num-of-cylinders',
 'engine-size',
 'fuel-system',
 'bore',
 'stroke',
 'compression-ratio',
 'horsepower',
 'paek-rmp',
 'city-mpg',
 'highway-mpg',
 'price']

In [ ]:
# Réimportez les données tout en spécifiant les noms des colonnes

df = pd.read_csv(file, header = None, names = colones)

# Affichez les premières cinq lignes de la dataframe

df.head()

,symbling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,paek-rmp,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [24]:
# Afficher les dernières lignes
df.tail(10)

,symbling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,paek-rmp,city-mpg,highway-mpg,price
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

Pour finir cette première partie concernar l'importation des données en tant que dataframe, vous devez sauvegarder la dataframe au format csv afin de pouvoir l'utiliser ultérieurement. Pour réaliser cette tâche de sauvegarde, vous utiliserez la méthode <strong>to_csv()</strong>

In [25]:
# Sauvegarder de la dataframe au format csv

df.to_csv('automibile.csv', index = False)

Le code ci-dessus m'a permis de sauvegarder la dataframe sous le nom automobile.csv dans un dossier précis de mon Drive. Ici, l'argument <strong>index</strong> a pour <strong>False</strong> car la dataframe contient déjà des indices lignes et on ne vaut pas en créer d'autres.

<h1 style="font-size:20; text-align:center; color:red; font-family:bold">Importation basique sur la structure des données</h1>

Aprés avoir importé les données et les sauvegarder, vous devez maintenant obtenir des informations sur la structure des données. Commencez d'abord par importer le fichier sauvegardé précédement

In [30]:
# Importez votre fichier sauvegardé

auto = pd.read_csv('automibile.csv')
auto.head()

,symbling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,paek-rmp,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

Répondez aux question ci-deeous en écrivant préalablement les codes adéquats

<h1>Question 1: Quel est le nombre de lignes et de colonnes de la dataframe?</h1>

In [31]:
# Affichez le nombre de lignes et de colonnes de la dataframe

auto.shape

(205, 26)

<h1>Question 2: Quel est le type dans chaque colonne?</h1>

In [33]:
auto.dtypes

symbling               int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
paek-rmp              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

<h1>Question 3: Comment avoir un résumé concis donnat les informations basiques sur la structure de la dataframe?</h1>

In [35]:
# Résumé concis sur les informations basiques de la dataframe

auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symbling           205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  paek-rmp           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

<h1 style="font-size:20; text-align:center; color:red; font-family:bold">Manipulation de la dataframe</h1>

Vous allez opérer des manipulations sur une copie de la dataframe <strong>df</strong>. Pour créer cette copie, utilisez la méthide <strong>.copy()</strong>

In [36]:
# Créez une copie de la dataframe df

df_copy = df.copy()

# Affichez les 5 dernières lignes de df_copy

df_copy.head()

,symbling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,paek-rmp,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [38]:
# Supprimez les colonnes 'symboling' et 'normalized-losses' de la dataframe df_copy

df_copy.drop(['symbling', 'normalized-losses'],axis = 1, inplace = True)

# Vérifiez que la suppression a été faite
df_copy.head()

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,paek-rmp,city-mpg,highway-mpg,price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450